### ISSUE TITLE
No bookmarks after upgrade to 3.2 (linkding)

### ISSUE THREAD

**Issue by abonhote** [fibelatti/pinboard-kotlin#337] opened 2024-10-09 00:16 UTC
Had to downgrade to the previous apk. Looks like a regression issue.

**Comment by WhatNoItsMe** [comment] 2024-10-09 01:25
Same here. I'm using it with a self-hosted linkding instance. 3.1.1 still works fine.
Android 14. Google Pixel 9 Pro XL

**Comment by djl** [comment] 2024-10-10 11:18
I might be running into this as well with my self-hosted instance but the issue started with the last 3.1 release.

**Comment by fibelatti** [comment] 2024-10-10 20:03
@abonhote @WhatNoItsMe @djl thanks for reporting this issue. I'm looking into it to have a fix released asap. Apologies for the inconvenience in the meantime.

**Comment by abonhote** [comment] 2024-10-10 20:04
No worries, it's a piece of software, and software has bugs. Completely normal.

**Comment by fibelatti** [comment] 2024-10-10 20:47
@abonhote @WhatNoItsMe @djl ok, I believe I have identified and fixed the root cause of the issue. Would you mind checking the latest release (https://github.com/fibelatti/pinboard-kotlin/releases/tag/v3.2.1) and let me know if the app works as expected?

**Comment by WhatNoItsMe** [comment] 2024-10-10 21:35
> @abonhote @WhatNoItsMe @djl ok, I believe I have identified and fixed the root cause of the issue. Would you mind checking the latest release (https://github.com/fibelatti/pinboard-kotlin/releases/tag/v3.2.1) and let me know if the app works as expected?

I just tried this version and it displays some bookmarks but not all, and they all have a date/time of when I refreshed the app. I also tried clearing cache/storage on the app and logging in anew but I get the same results.

**Comment by fibelatti** [comment] 2024-10-10 21:58
@WhatNoItsMe thanks for trying it out. I'm not able to reproduce that date issue, but let me continue investigating.

**Comment by abonhote** [comment] 2024-10-11 03:07
I can confirm the date issue - nice catch, didn't see that one. Apart from that, it looks good 👍🏻

**Comment by djl** [comment] 2024-10-11 08:25
Other than the date issue mentioned above, this is working great. Thanks!

**Comment by fibelatti** [comment] 2024-10-11 11:01
@abonhote @WhatNoItsMe @djl thanks everyone for checking. I hope to have a fix for the date issue later today

**Comment by fibelatti** [comment] 2024-10-11 23:29
Hi @abonhote @WhatNoItsMe @djl thanks for you patience with this issue. Hopefully the latest release will have the dates sorted out https://github.com/fibelatti/pinboard-kotlin/releases/tag/v3.2.2

**Comment by abonhote** [comment] 2024-10-12 04:50
Works perfectly fine now, thanks 👍🏻

**Comment by onjour** [comment] 2024-10-12 07:44
Had the same issue and it works perfectly well for me as well, many thanks for the quick fix 👌

**Comment by fibelatti** [comment] 2024-10-12 09:16
Thanks for confirming folks!

**Closed** 2024-10-12 09:17 UTC
Labels: bug
